apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-depl
  namespace: synchrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  template:
    metadata:
      labels:
        app: workspace
    spec:
      containers:
        - name: workspace-container
          image: 565393066924.dkr.ecr.ap-northeast-2.amazonaws.com/synchrome-workspace:latest #바꿔야함
          ports:
            - containerPort: 8080
          resources:
            # 컨테이너가 사용할수 있는 리소스의 최대치
            limits:
              cpu: "1"
              memory: "500Mi"
            # 컨테이너가 시작될떄 보장받아야 하는 최소 자원
            requests:
              cpu: "0.5"
              memory: "250Mi"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: synchrome-secrets
                  key: DB_HOST

            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: synchrome-secrets
                  key: DB_PW

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: synchrome-secrets
                  key: JWT_SECRET_KEY

            - name: JWT_SECRET_RT_KEY
              valueFrom:
                secretKeyRef:
                  name: synchrome-secrets
                  key: JWT_SECRET_RT_KEY

            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: synchrome-secrets
                  key: GOOGLE_SECRET

            - name: AWS_KEY
              valueFrom:
                secretKeyRef:
                  name: synchrome-secrets
                  key: AWS_KEY

            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: synchrome-secrets
                  key: AWS_SECRET

            # - name: S3_BUCKET
            #   valueFrom:
            #     secretKeyRef:
            #       name: synchrome-secrets
            #       key: S3_BUCKET
          
          # 컨테이너 상태 확인
          readinessProbe:
            httpGet:
              # healthcheck 경로
              path: /workspace/health
              port: 8080
            # 컨테이너 시작 후 지연
            initialDelaySeconds: 10
            # 확인 반복 주기
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  namespace: synchrome
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: workspace