spring:
  redis:
    port: 6379
    host: localhost
  datasource:
    url: jdbc:mariadb://localhost:3306/livechat?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
  application:
    #    member-service?? ???? eureka? ??
    name: member-service
#  kafka:
#    kafka-server: localhost:9092
#    consumer:
#      #      groupid? ??? ??? ???? ID??, ??? ?? ID? ?? ????? ???? ???? consume.
#      group-id: member-group
#      #      ?? ??? ??? ????? ?? ?? (latest: ??? ??? ???? ???? ??)
#      auto-offset-reset: earliest
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Seoul

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

jwt:
  expiration: 1000
  #  ???? ?? 32? ?? ??.(???? ??)
  #  beyondaccesstoeknsecretkeybeyondaccesstoeknsecretkeybeyondaccesstoeknsecretkeybeyondaccesstoeknsecretkey
  secretKey: YmV5b25kYWNjZXNzdG9la25zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2VrbnNlY3JldGtleWJleW9uZGFjY2Vzc3RvZWtuc2VjcmV0a2V5YmV5b25kYWNjZXNzdG9la25zZWNyZXRrZXk=
  expirationRT: 288000
  #  ???? ?? 32? ?? ??.(???? ??)
  #  beyondrefreshsecrettokenkeybeyondrefreshsecrettokenkeybeyondrefreshsecrettokenkey
  secretKeyRT: YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5

oauth:
  google:
    client-id: 752078374240-4tdtnn7i8de5jpavh9qbupu7nbimt5rn.apps.googleusercontent.com
    client-secret: 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
    redirect_uri: http://localhost:3000/oauth/google/redirect