spring:
  redis:
    port: 6379
    host: redis-service
  datasource:
    url: jdbc:mariadb://${DB_HOST}:3306/user?serverTimezone=Asia/Seoul
    username: admin
    password: ${DB_PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    show_sql: true
  application:
    name: user-service
#  kafka:
#    kafka-server: localhost:9092
#    consumer:
#      group-id: user-group
#      auto-offset-reset: earliest
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Seoul

server:
  port: 8080

eureka:
  client:
    enabled: false

iamport:
  api_key: ${PAYMENT_KEY}
  api_secret: ${PAYMENT_SECRET}

jwt:
  expiration: 1000
  #  ???? ?? 32? ?? ??.(???? ??)
  #  beyondaccesstoeknsecretkeybeyondaccesstoeknsecretkeybeyondaccesstoeknsecretkeybeyondaccesstoeknsecretkey
  secretKey: YmV5b25kYWNjZXNzdG9la25zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2VrbnNlY3JldGtleWJleW9uZGFjY2Vzc3RvZWtuc2VjcmV0a2V5YmV5b25kYWNjZXNzdG9la25zZWNyZXRrZXk=
  expirationRT: 288000
  #  ???? ?? 32? ?? ??.(???? ??)
  #  beyondrefreshsecrettokenkeybeyondrefreshsecrettokenkeybeyondrefreshsecrettokenkey
  secretKeyRT: YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5YmV5b25kcmVmcmVzaHNlY3JldHRva2Vua2V5

oauth:
  google:
    client-id: 752078374240-4tdtnn7i8de5jpavh9qbupu7nbimt5rn.apps.googleusercontent.com
    client-secret: ${GOOGLE_SECRET}
    redirect_uri: https://www.synchrome.shop/oauth/google/redirect
#뭘까
cloud:
  aws:
    s3:
      bucket: stomachforce
    credentials:
      access-key: AKIAT4GVRVENSQ6EB6P6
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false