eureka:
  client:
    enabled: false

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'https://www.synchrome.shop'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowedCredentials: true
      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
          uri: http://user-service

        - id: collabcontent-service
          predicates:
            - Path=/collabcontent-service/**
          filters:
            - StripPrefix=1
          uri: http://collabcontent-service

        - id: workspace-service
          predicates:
            - Path=/workspace-service/**
          filters:
            - StripPrefix=1
          uri: http://workspace-service
      httpserver:
        websocket:
          max-frame-payload-length: 65536

jwt:
  secretKey: ${JWT_SECRET_KEY}