spring:
  data:
    redis:
      port: 6379
      host: localhost
  datasource:
    url: jdbc:mariadb://localhost:3306/livechat?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Seoul

openvidu:
  url: http://localhost:4443
  secret: 1234
