spring:
  application:
    name: collabcontent-service
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/chatdb
    username: root
    password: 1234
  jpa:
    database: mysql
    #    InnoDB
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  kafka:
    bootstrap-servers: localhost:9092  # ✅ 카프카 서버 주소
    consumer:
      group-id: chat-group             # ✅ 컨슈머 그룹 ID
      auto-offset-reset: latest        # earliest | latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0

openvidu:
  url: http://localhost:4443
  secret: 1234

jwt:
  secretKey: YmV5b25kYWNjZXNzdG9la25zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2VrbnNlY3JldGtleWJleW9uZGFjY2Vzc3RvZWtuc2VjcmV0a2V5YmV5b25kYWNjZXNzdG9la25zZWNyZXRrZXk
cloud:
  aws:
    s3:
      bucket: hans-ordersystem-image
    credentials:
      access-key: AKIA2AUOPD3OP5O6TQG2
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false