spring:
  application:
    #    user-service?? ???? eureka? ??
    name: collabcontent-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# port ?? 0?? ??? ??????? port ??
server:
  port: 0
