spring:
  redis:
    port: 6379
    host: localhost
  datasource:
    url: jdbc:mariadb://localhost:3306/workspace?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    show_sql: true
  servlet:
    multipart: # ✅ 이 부분 추가!
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: workspace-service
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Seoul


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# port ?? 0?? ??? ??????? port ??
server:
  port: 0
cloud:
  aws:
    s3:
      bucket: stomachforce
    credentials:
      access-key: AKIAT4GVRVENSQ6EB6P6
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
