spring:
  redis:
    port: 6379
    host: localhost
  datasource:
    url: jdbc:mariadb://localhost:3306/workspace?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    show_sql: true
  application:
    #    user-service?? ???? eureka? ??
    name: workspace-service
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Seoul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# port ?? 0?? ??? ??????? port ??
server:
  port: 0
